- Python-Ebooks-Converter/epub2pdf.py
Made an Ebook Convertor that converts Ebooks from .epub (kindle format) to .pdf for reading on multiple devices.
Uses convertAPI at the backend to do the conversion
> Epub to PDF converter in Python

- Deep Web Crawler/Crawl.py
- Deep Web Crawler/GUI.py
A python project which can recursively crawl all the hyperlinks of the web page and generate txt files of all the tags values present in the page. It takes a base link as input and recursively go through all the links found in the html.
> Adding Deep web crawling project

- covid-statewise-api/app.py
Made this small project using flask and bs4 that scraps covid stats data from mygov.in and returns a json format data
> Added Covid-India-Statewise-Api

- survey/cssforms.css
- survey/surveyform.html
Survey Form which used to take inputs from user
> Survey Form in HTML and CSS

- Space-Invaders/README.md
- Space-Invaders/index.html
- Space-Invaders/sapce_invaders_models.js
- Space-Invaders/spaceinvaders.js
I added the Space Invaders game made in JavaScript :)
> JavaScript Space Invaders Game

- Instagram_scraper/README.md
- Instagram_scraper/Scraper.py
I have added a python script to scrape Instagram account information using graphql endpoint without any external dependency.
For issues #13
> Added Instragram Scraper

- Python Basics Begineer Programs/Binary Search Functions.py
i created a small file containing a program for binary search but through function. so that user can use that on multiple IDEs and more efficiently.
Thank You And please accept My Pull request.
> Program For Pyhton User

- Simple_PDF to Audiobok Convertor/PDF_Audiobook_Converter.py
Learning a Research Paper or E-books is one of the Least Attracting Things we do. Though, we hate it, we definitely using it daily. Thus, being a Python Developer, let's convert it to a Free to use Audio-Book. Let's only use our sharp ears rather than scrolling our eyeballs through a magnifier. Also, will be helpful to Bling guy who wants to learn a 25 paged AI Research papers and more.
> Simple_Program_to Convert PDF to AudioBooks.

- shuffle.py
Hello there again!! I am adding a simple program in Python which generates 5 cards by shuffling them among the deck. :+1:
> Adding a Program for Shuffling a Deck of Cards

- Password validator/pass_validator.py
password validator using tkinter module of python, which compare given password with provided conditions
> pass validator tkinter

- Python Basics Begineer Programs/Sum of Array.py
Hi there!
i'm adding python code for add up array using for loop
> Added Sum of Array

- blog section using tailwind css
Hey I am adding a new components (blog section using tailwind css)
> Added blog section using tailwind css

- LoginRegisterPage/login.html
- LoginRegisterPage/register.html
- LoginRegisterPage/style.css
Added login page and register page to use in any modern website
If I have done anything wrong in a way please let me know.
Thank you
> LoginRegister Page to use in any modern website

- Color_picker/colorpicker.py
Pick any color displayed on screen and display it's RGB/Hex value. Written in python.
> Color picker tool

- Google Assistant Clone/index.html
- Google Assistant Clone/script.js
- Google Assistant Clone/style.css
Hey, there mate!! I am now adding a Google Assistant Clone. Cheers :) :+1:
> Added a Google Assistant Clone

- scanner.py
which is finds that which ports are malicious or not.
> created malicious port scanner

- java-programs/EvenOdd.java
:rocket:  Add even odd program under java-programs folder
> :rocket:Add even odd program under java-programs folder 

- MINI-IMDB/README.md
- MINI-IMDB/imdb.py
IT IS A MINI-IMDB PROJECT THAT PROVIDES INFORMATION ABOUT ANY MOVIE OR TV SERIES WHEN SEARCHED.
This project is coded in python language and uses basics of python data structure - lists, OOPS and some basics of database.
Do remember to go through README.md for better understanding.
> Automating movies and TV series search using python script

- REV-Chall/Proper_algo.c
added a ctf rev chall source code
> CTF-Reverse-chall-source-code

- Color-Game-master/README.md
- Color-Game-master/colorGame.css
- Color-Game-master/colorGame.html
- Color-Game-master/colorGame.js
Adding Color Guessing Game made using HTML, CSS, JavaScript.
> Color Game

- java-programs/BubbleSort.java
- java-programs/CentralTendencyMeasures.java
- java-programs/DiamondPattern.java
- java-programs/SelectionSort.java
These include two sorting algorithms (bubble and selection sort)
Central Tendency measures calculation
Displaying a diamond pattern
> Added Java programs

- survey/surveyform.html
Alert Box:  <div class="alert alert-success">
<strong>Great!</strong> Can you register <a href="https://hacktoberfest.digitalocean.com/">Hacktoberfest 2020</a> before pull request.
</div>
> Some Changes and add in your repository

- Scrabble Scoreboard/Scrabble Scoreboard.css
- Scrabble Scoreboard/Scrabble Scoreboard.html
- Scrabble Scoreboard/Scrabble Scoreboard.js
Scrabble Scoreboard is a fun way to keep track of your scoring totals and word history
- This project is a scoreboard only and does not include the actual game. This is meant to accompany the scrabble game either online or in person
- User is able to select basic avatars by clicking on the avatar icons (base profiles can be updated in the "Scrabble Scoreboard.css" and "Scrabble Scoreboard.js" files)
> Scrabble Scoreboard

- 24hr clock
Python program to convert time from 12 hour to 24 hour format
> 24 hr Clock

- Text Shadow Project/index.html
This project contains JS and CSS within html only and it automatically creates 4 colorful shadows of text when move the arrow.
> Text Shadow

- Live Clock/index.html
Made with JS and CSS added in html file using style and script tags
> Live Clock 

- Speech Synthesiser/index.html
> Speech Synthesiser 

- Voice-recognition-JS-master/README.md
- Voice-recognition-JS-master/app.js
- Voice-recognition-JS-master/index.html
A voice recognition tool for web pages
> new request

- Amazon-price-notification-master/README.md
- Amazon-price-notification-master/amazonprices.py
A price notification bot for amazon or any other online retail platform for email notification on your email
> pricenotificationbot

- Python_programs/valid_parenthesis.py
Adding Valid parenthesis program.
> adding valid parenthesis

- Python_programs/merge_sort.py
> merge sort implementation

- pixelartmaker/README.md
- pixelartmaker/app.js
- pixelartmaker/index.html
- pixelartmaker/style.css
> Adding PixerlArtMaker

- Python_programs/next_permutation.py
Implementing next permutation in which numbers are rearranged lexographically.
> Rearranges numbers lexographically

- List Checker/index.html
Press shift to select to choose multiple choices
> List Checker project using JS without libraries

- SecuPi/Camera.py
- SecuPi/Mail_Handle.py
- SecuPi/README.md
- SecuPi/Runner.py
- SecuPi/Secupi.py
- SecuPi/embed.html
- SecuPi/essential_imports.py
The project aims at providing prompts to its user whenever his/her door bell is rung. It was developed under the Project Based Learning (PBL) scheme of my university, which was to be taken up as a second semester course. The code is well documented and speaks for itself.  Also, all the flaws have been highlighted for improvement. Please accept my Pull Request. Thanks! :)
> Secupi: A Trigger-Based Home Security system using Python 3 and Telegram Bots

- Calculator/index.html
make it a responsive calculator for any device screen size
> "added compatible screen"

- Calculator/Angular_Calculator.html
Created the calculator using HTML  and Angular JS
> Calculatoor

- Air Travel Feedback/FeedbackForm.html
- Air Travel Feedback/styles.css
Added Air Travel Feedback folder with FeedbackForm.html and styles.css
> Added Air Travel Feedback folder

- java-programs/.gitignore
- java-programs/DiamondPattern.java
- java-programs/SecretSantaRandomPairsGenerator.java
Added [Secret Santa](https://en.wikipedia.org/wiki/Secret_Santa) Random Pairs Generator Java Program.
Example output below:
```
==================================
Behold! Fate decided the following: 
==================================
Bob prepares a gift for Gregory
Samanta prepares a gift for Ross
Ross prepares a gift for Bob
Gregory prepares a gift for Samanta
==================================
Happy NY, kids! Ho-ho-ho!
==================================
```
Fixed compilation errors in `DiamondPattern.java` program
> Added Secret Santa Random Pairs Generator Java Program

- helloWorldSwift.playground/Contents.swift
- helloWorldSwift.playground/contents.xcplayground
> hello world in swift

- Tip Calculator JS/index.html
- Tip Calculator JS/script.js
Add split bill feature in the calculator
> added split bill

- PythonPrgForParticularDigitInRange.py
This program helps you determine whether the particular digit exists in the range of given numbers or not.
This program has 1, 4, 9 as the digit and you can take range as anything
eg;- 100 to 200 the numbers are 111,114,119,141,144,149,191,194,199. So the answer is 9
> Python Program For Particular Digit In Range

- TODO list/index.html
- TODO list/index.js
Add MomentJS to show today date in To Do List
> added moment js to show date

- random_password_generator/app.js
> Some Changes on this file hacktoberfest

- responsive_img_gallery/app.js
- responsive_img_gallery/index.html
- responsive_img_gallery/style.css
This is a responsive random image gallery project. 
I used the ES6 and CSS grid in this project and the resource of our images is from unplash.com.
> Responsive random img gallery

- EncryptDecrypt/Passowrd security with Encryption.py
@vijaygupta18
Hi Vijay,
I have Added an Encryption and Decryption code for password security in python. Can you please accept my merge request.
Thanks
AvinashSingh
> Added an Encryption and Decryption code for password security in python

- Global Gapminder Data Extreme EDA/Readme.md
Global Gapminder Data Extreme EDA added
> Global Gapminder Data Extreme EDA 

- weather-app/.gitignore
- weather-app/README.md
- weather-app/app.js
- weather-app/package-lock.json
- weather-app/package.json
- weather-app/utils/forecast.js
- weather-app/utils/geocode.js
A node.js application to check weather by simply providing the address using cli.
> jainayu: weather app using on cli

- reaction_time_tester
A game to test your reaction time, made  using HTML,CSS and JS
> Reaction_Time_Tester_Game

- Happy Penguin/Penguin.html
It's a basic Penguin Animation.
> Added Happy Penguin

- Python List Function by user input
This program is in Python.
It will ask For the no. of NAMES (Strings).
Which then count each NAME user will enter, and show the NAMES NUMBER whose count is greater than 5.
> Python List Function by user input

- Thai_Numerology/index.html
- Thai_Numerology/script.js
- Thai_Numerology/style.css
I have finished my project for Thai numerology, this project is a tool for fortune teller in Thailand.
> Thai numerology
